### ISSUE TITLE
Error if a line contains only white-spaces.

### ISSUE THREAD

**Issue by pintarj** [damianobarbati/envk#5]
The current implementation throws an error if a line contains only white-spaces _(a line with some spaces or tabulation without any visible character)_. Maybe it would be better to ignore those lines.

So instead of `.filter(Boolean)` something like `.filter(RegExp.prototype.test.bind(/[^\s]/))`. 

Saluti.

**Comment by damianobarbati** [comment]
@pintarj it should be solved, `\t` and spaces are properly trimmed.
